on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17 ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: API Server Test
        run: go test ./...
        working-directory: ./apiserver
      - name: Control Manager Test
        run: go test ./...
        working-directory: ./controlmanager
